version: "3"

services:

  video_service:
    build:
      dockerfile: Dockerfile
      context: video_service/
    environment:
      RTMP_SERVER_ADDR: ":1935"
    ports:
      - 8081:80
    networks:
      - mynet
  
  web:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8082:80"
    networks:
      - mynet

networks:
    mynet: