version: "3"

services:

  manager_service:
    build:
      dockerfile: Dockerfile
      context: manager_service/
    ports:
      - 7191:7191
    networks:
      - mynet

  video_service:
    build:
      dockerfile: Dockerfile
      context: video_service/
    environment:
      RTMP_SERVER_ADDR: ":1935"
    ports:
      - 1935:1935
      - 8081:80
    volumes:
      - ./hls:/hls
    networks:
      - mynet
  
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./hls:/hls
    ports:
      - "8082:8080"
    networks:
      - mynet

networks:
    mynet: