version: "3"

services:

  manager_service:
    build:
      dockerfile: Dockerfile
      context: manager_service/
    environment:
      HOST: "localhost"
    ports:
      - 7191:7191
    volumes:
      - ./manager_service/http/templates:/templates
    networks:
      - mynet

  video_service:
    build:
      dockerfile: Dockerfile
      context: video_service/
    environment:
      RTMP_SERVER_ADDR: ":1935"
      HOST: "localhost"
    ports:
      - 1935:1935
      - 8081:80
    volumes:
      - ./hls:/hls
    networks:
      - mynet

  chat_service:
    build:
      dockerfile: Dockerfile
      context: chat_service/
    environment:
      HOST: "localhost"
    ports:
      - "9080:9080"
    networks:
      - mynet
    depends_on:
      - manager_service

  chat_handler:
    build:
      dockerfile: DockerfileHandler
      context: chat_service/
    environment:
      HOST: "localhost"
    ports:
      - "7192:7192"
    networks:
      - mynet
    depends_on:
      - chat_service

  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./hls:/hls
    ports:
      - "8082:8080"
    networks:
      - mynet

networks:
    mynet: